highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /cv/
title: Jan-Arve Nygård's Resume
name: Jan-Arve Nygård
email: jan@ridabu.no
email_full: mailto:jan@ridabu.no
website: github.io/jannyg
website_full: https://jannyg.github.io
github: trending
twitter: twitter
tel: +47 99 28 13 66
tel_full: tel:+4799281366

# needed for travis-ci build
exclude: [vendor]
